In [1]:
import anndata

from anndata import AnnData

# Load h5ad file
adata = anndata.read_h5ad("/home/fgsasse_lrs_1/Downloads/BA/BA_data/RNA/zf_multiome_atlas_full_RNA_v1_release.h5ad")
adata

AnnData object with n_obs × n_vars = 94562 × 32057
    obs: 'developmental_stage', 'dataset', 'zebrafish_anatomy_ontology_class', 'zebrafish_anatomy_ontology_class_coarse', 'timepoint', 'n_genes_by_counts', 'total_counts', 'total_counts_mt', 'pct_counts_mt', 'total_counts_nc', 'pct_counts_nc'
    var: 'features', 'mt', 'nc', 'n_cells_by_counts', 'mean_counts', 'pct_dropout_by_counts', 'total_counts'
    uns: 'dataset_colors', 'log1p', 'zebrafish_anatomy_ontology_class_coarse_colors', 'zebrafish_anatomy_ontology_class_colors'
    obsm: 'X_umap_atac', 'X_umap_joint', 'X_umap_rna'
    layers: 'counts'

In [12]:
adata.obs

,developmental_stage,dataset,zebrafish_anatomy_ontology_class,zebrafish_anatomy_ontology_class_coarse,timepoint,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,total_counts_nc,pct_counts_nc
AAACAGCCACCTAAGC-1_1,15somites,TDR118,epidermis,epidermis,16hpf,2317,6522.0,160.0,2.453235,726.0,11.131555
AAACAGCCAGGGAGGA-1_1,15somites,TDR118,pronephros,pronephros,16hpf,2319,6100.0,245.0,4.016393,1051.0,17.229508
AAACAGCCATAGACCC-1_1,15somites,TDR118,hindbrain,hindbrain,16hpf,3467,12581.0,779.0,6.191877,2542.0,20.205071
AAACATGCAAACTCAT-1_1,15somites,TDR118,spinal_cord,spinal_cord,16hpf,2145,5642.0,265.0,4.696916,1075.0,19.053527
AAACATGCAAGGACCA-1_1,15somites,TDR118,neural_optic2,neural_optic,16hpf,838,2691.0,181.0,6.726124,732.0,27.201784
...,...,...,...,...,...,...,...,...,...,...,...
TTTGTGTTCCCTCAGT-1_7,10somites,TDR128,tail_bud,tail_bud,14hpf,1281,3079.0,114.0,3.702501,572.0,18.577460
TTTGTTGGTACCTTAC-1_7,10somites,TDR128,lateral_plate_mesoderm,lateral_plate_mesoderm,14hpf,2441,6276.0,179.0,2.852135,962.0,15.328235
TTTGTTGGTATTGAGT-1_7,10somites,TDR128,neural_posterior,neural_posterior,14hpf,1164,2377.0,74.0,3.113168,217.0,9.129154
TTTGTTGGTGCGCGTA-1_7,10somites,TDR128,endocrine_pancreas,endocrine_pancreas,14hpf,811,1750.0,54.0,3.085714,182.0,10.400000
TTTGTTGGTTAAGGCC-1_7,10somites,TDR128,somites,somites,14hpf,2399,8999.0,357.0,3.967107,1001.0,11.123458

In [2]:
import os
rna_dir="/home/fgsasse_lrs_1/Downloads/BA/BA_data/RNA"
os.makedirs(rna_dir, exist_ok=True)

In [3]:
# Save observations (cells)
cells = adata.obs
cells.to_csv(os.path.join(rna_dir, "cells.tsv"), sep="\t", index=True, header=False)

In [4]:
# Save features (genes)
features = adata.var
features.to_csv(os.path.join(rna_dir, "features.tsv"), sep="\t", index=False, header=False)

In [5]:
# Save as matrix market format
from scipy.io import mmwrite
mmwrite(os.path.join(rna_dir, "matrix.mtx"), adata.layers["counts"])

In [7]:
cells

,developmental_stage,dataset,zebrafish_anatomy_ontology_class,zebrafish_anatomy_ontology_class_coarse,timepoint,n_genes_by_counts,total_counts,total_counts_mt,pct_counts_mt,total_counts_nc,pct_counts_nc
AAACAGCCACCTAAGC-1_1,15somites,TDR118,epidermis,epidermis,16hpf,2317,6522.0,160.0,2.453235,726.0,11.131555
AAACAGCCAGGGAGGA-1_1,15somites,TDR118,pronephros,pronephros,16hpf,2319,6100.0,245.0,4.016393,1051.0,17.229508
AAACAGCCATAGACCC-1_1,15somites,TDR118,hindbrain,hindbrain,16hpf,3467,12581.0,779.0,6.191877,2542.0,20.205071
AAACATGCAAACTCAT-1_1,15somites,TDR118,spinal_cord,spinal_cord,16hpf,2145,5642.0,265.0,4.696916,1075.0,19.053527
AAACATGCAAGGACCA-1_1,15somites,TDR118,neural_optic2,neural_optic,16hpf,838,2691.0,181.0,6.726124,732.0,27.201784
...,...,...,...,...,...,...,...,...,...,...,...
TTTGTGTTCCCTCAGT-1_7,10somites,TDR128,tail_bud,tail_bud,14hpf,1281,3079.0,114.0,3.702501,572.0,18.577460
TTTGTTGGTACCTTAC-1_7,10somites,TDR128,lateral_plate_mesoderm,lateral_plate_mesoderm,14hpf,2441,6276.0,179.0,2.852135,962.0,15.328235
TTTGTTGGTATTGAGT-1_7,10somites,TDR128,neural_posterior,neural_posterior,14hpf,1164,2377.0,74.0,3.113168,217.0,9.129154
TTTGTTGGTGCGCGTA-1_7,10somites,TDR128,endocrine_pancreas,endocrine_pancreas,14hpf,811,1750.0,54.0,3.085714,182.0,10.400000
TTTGTTGGTTAAGGCC-1_7,10somites,TDR128,somites,somites,14hpf,2399,8999.0,357.0,3.967107,1001.0,11.123458

In [9]:
features

,features,mt,nc,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts
ptpn12,ptpn12,False,False,395,0.004241,99.582285,401.0
phtf2,phtf2,False,False,342,0.003648,99.638333,345.0
phtf2.1,phtf2.1,False,False,715,0.007688,99.243882,727.0
CU856344.1,CU856344.1,False,False,58,0.000613,99.938665,58.0
si:zfos-932h1.3,si:zfos-932h1.3,False,False,447,0.004780,99.527294,452.0
...,...,...,...,...,...,...,...
mt-nd6,mt-nd6,True,False,24034,0.349422,74.583871,33042.0
NC-002333.21,NC-002333.21,False,True,121,0.001290,99.872042,122.0
mt-cyb,mt-cyb,True,False,94421,19.444745,0.149109,1838734.0
NC-002333.22,NC-002333.22,False,True,152,0.001607,99.839259,152.0
NC-002333.11,NC-002333.11,False,True,159,0.001681,99.831856,159.0

In [10]:
#loading other h5ad file
bdata = anndata.read_h5ad("/home/fgsasse_lrs_1/Downloads/BA/BA_data/zf_atlas_full_v1_release.h5ad")
bdata

import os
rna_dir="/home/fgsasse_lrs_1/Downloads/BA/BA_data/RNA_new"
os.makedirs(rna_dir, exist_ok=True)

# Save observations (cells)
cells = bdata.obs
cells.to_csv(os.path.join(rna_dir, "cells.tsv"), sep="\t", index=True, header=False)

# Save features (genes)
features = bdata.var
features.to_csv(os.path.join(rna_dir, "features.tsv"), sep="\t", index=False, header=False)

# Save as matrix market format
from scipy.io import mmwrite
mmwrite(os.path.join(rna_dir, "matrix.mtx"), bdata.X)

In [11]:
features

,gene_ids,feature_types,genome,mt,nc,n_cells_by_counts,mean_counts,pct_dropout_by_counts,total_counts,n_cells
ptpn12,ENSDARG00000102141,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,1552,0.013193,98.713858,1592.0,1552
phtf2,ENSDARG00000102123,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,195,0.001624,99.838404,196.0,195
phtf2-1,ENSDARG00000114503,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,2821,0.024803,97.662239,2993.0,2821
CU856344.1,ENSDARG00000115971,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,44,0.000365,99.963537,44.0,44
si:zfos-932h1.3,ENSDARG00000098311,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,2299,0.019864,98.094820,2397.0,2299
...,...,...,...,...,...,...,...,...,...,...
NC_002333.22,ENSDARG00000083462,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,True,943,0.008047,99.218536,971.0,943
NC_002333.11,ENSDARG00000081475,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,True,343,0.002859,99.715756,345.0,343
dTomato,dTomato,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,4,0.000033,99.996685,4.0,4
mCerulean,mCerulean,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,0,0.000000,100.000000,0.0,0
EYFP,EYFP,Gene Expression,Danio.rerio_genome_Zebrabow_6,False,False,0,0.000000,100.000000,0.0,0

In [1]:
#loading ATAC h5ad file
import anndata

from anndata import AnnData

cdata = anndata.read_h5ad("/home/fgsasse_lrs_1/Downloads/BA/BA_data/ATAC/zf_multiome_atlas_full_ATAC_v1_release.h5ad")
cdata

AnnData object with n_obs × n_vars = 94562 × 640834
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'nCount_SCT', 'nFeature_SCT', 'global_annotation', 'nCount_peaks_bulk', 'nFeature_peaks_bulk', 'nCount_peaks_celltype', 'nFeature_peaks_celltype', 'nCount_peaks_merged', 'nFeature_peaks_merged', 'SCT.weight', 'peaks_merged.weight', 'nCount_Gene.Activity', 'nFeature_Gene.Activity', 'nCount_peaks_integrated', 'nFeature_peaks_integrated', 'dataset', 'integrated.weight', 'peaks_integrated.weight', 'wsnn_res.0.8', 'seurat_clusters', 'leiden_0.5', 'leiden_0.8', 'leiden_1', 'leiden_1.2', 'leiden_1.5', 'leiden_2', 'leiden_3', 'leiden_4', 'leiden_5', 'leiden_6', 'leiden_7', 'leiden_8', 'leiden_9', 'leiden_10', 'leiden_0.5_merged', 'leiden_0.8_merged', 'leiden_1_merged', 'leiden_1.2_merged', 'leiden_1.5_merged', 'leiden_2_merged', 'leiden_3_merged', 'leiden_4_merged', 'leiden_5_merged', 'leiden_6_merged', 'leiden_7_merged', 'leiden_8_merged', 'leiden_9_merged', 'leiden_10_merged', 'annotation_ML_coarse', 'dev_stage'
    layers: 'counts'

In [ ]:
cells = []
with open("/home/fgsasse_lrs_1//output.txt", "r") as f:
    for line in f:
        cells.append(line.strip())

cells


fildata = cdata[cells, :]

View of AnnData object with n_obs × n_vars = 2 × 640834
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'nCount_ATAC', 'nFeature_ATAC', 'nucleosome_signal', 'nucleosome_percentile', 'TSS.enrichment', 'TSS.percentile', 'nCount_SCT', 'nFeature_SCT', 'global_annotation', 'nCount_peaks_bulk', 'nFeature_peaks_bulk', 'nCount_peaks_celltype', 'nFeature_peaks_celltype', 'nCount_peaks_merged', 'nFeature_peaks_merged', 'SCT.weight', 'peaks_merged.weight', 'nCount_Gene.Activity', 'nFeature_Gene.Activity', 'nCount_peaks_integrated', 'nFeature_peaks_integrated', 'dataset', 'integrated.weight', 'peaks_integrated.weight', 'wsnn_res.0.8', 'seurat_clusters', 'leiden_0.5', 'leiden_0.8', 'leiden_1', 'leiden_1.2', 'leiden_1.5', 'leiden_2', 'leiden_3', 'leiden_4', 'leiden_5', 'leiden_6', 'leiden_7', 'leiden_8', 'leiden_9', 'leiden_10', 'leiden_0.5_merged', 'leiden_0.8_merged', 'leiden_1_merged', 'leiden_1.2_merged', 'leiden_1.5_merged', 'leiden_2_merged', 'leiden_3_merged', 'leiden_4_merged', 'leiden_5_merged', 'leiden_6_merged', 'leiden_7_merged', 'leiden_8_merged', 'leiden_9_merged', 'leiden_10_merged', 'annotation_ML_coarse', 'dev_stage'
    layers: 'counts'

In [ ]:
#loading ATAC h5ad file
import anndata

from anndata import AnnData

cdata = anndata.read_h5ad("/home/fgsasse_lrs_1/Downloads/BA/BA_data/ATAC/zf_multiome_atlas_full_ATAC_v1_release.h5ad")
cdata

import os
rna_dir="/home/fgsasse_lrs_1/Downloads/BA/BA_data/ATAC"
os.makedirs(rna_dir, exist_ok=True)

# Save observations (cells)
cells = cdata.obs
cells.to_csv(os.path.join(rna_dir, "cells.tsv"), sep="\t", index=True, header=False)

# Save features (genes)
features = cdata.var
features.to_csv(os.path.join(rna_dir, "features.tsv"), sep="\t", index=False, header=False)

# Save as matrix market format
#from scipy.io import mmwrite
#mmwrite(os.path.join(rna_dir, "matrix.mtx"), cdata.X.T)

In [10]:
cdata.X[:5, :5].toarray()

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Save as matrix market format
from scipy.io import mmwrite
mmwrite(os.path.join(rna_dir, "matrix.mtx"), cdata.X)